# Generated by Django 5.0.7 on 2024-07-16 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrera',
            name='anio',
        ),
        migrations.RemoveField(
            model_name='carrera',
            name='tecprof',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera'),
        ),
        migrations.RemoveField(
            model_name='materia',
            name='carrera',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='dni',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='llamado',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='materia',
        ),
        migrations.DeleteModel(
            name='AnioCarrera',
        ),
        migrations.DeleteModel(
            name='TecProf',
        ),
        migrations.DeleteModel(
            name='Carrera',
        ),
        migrations.DeleteModel(
            name='Inscripcion',
        ),
        migrations.DeleteModel(
            name='Llamado',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Mesa',
        ),
    ]
