# Generated by Django 5.0.7 on 2024-08-17 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0004_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='dni',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
