# Generated by Django 5.0.7 on 2024-07-16 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnioCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TecProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.aniocarrera')),
                ('tecprof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.tecprof')),
            ],
        ),
    ]
