# Generated by Django 5.0.7 on 2024-07-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aniocarrera',
            options={'verbose_name_plural': 'Año de la Carrera'},
        ),
        migrations.AlterModelOptions(
            name='tecprof',
            options={'verbose_name_plural': 'Tecnicaturas/Profesorados'},
        ),
    ]
