# Generated by Django 5.0.7 on 2024-07-16 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alumnos', '0002_remove_carrera_anio_remove_carrera_tecprof_and_more'),
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Llamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carreras.carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('llamado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.llamado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.alumno')),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.mesa')),
            ],
        ),
    ]
