# Generated by Django 5.0.7 on 2024-07-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_alter_inscripcion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamado',
            name='fecha',
            field=models.DateField(),
        ),
    ]
