# Generated by Django 5.0.7 on 2024-07-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_llamado_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llamado',
            name='hora',
            field=models.TimeField(),
        ),
    ]
