# Generated by Django 5.0.7 on 2024-08-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0007_alter_llamado_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(blank=True, choices=[('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='En revisión', max_length=20, null=True),
        ),
    ]
