# Generated by Django 5.0.7 on 2024-08-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0008_inscripcion_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='estado',
            field=models.CharField(blank=True, choices=[('En Revisión', 'En Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='En revisión', max_length=20, null=True),
        ),
    ]
