# Generated by Django 5.0.7 on 2024-08-15 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0012_inscripcion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='usuario',
        ),
    ]
