# Generated by Django 5.0.7 on 2024-08-16 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0016_inscripcion_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='usuario',
        ),
    ]
